---
 out_dir: '../model_parameters'
 vocab_path: "../vocab/database_selfies_vocab.yaml"
 datapath : "../generate_result"
 percentage: 1

 rnn_config:
  # size of vocab + <eos> + <sos> + <pad>
  # char: 48, regex:75, selfies:77
  num_embeddings: 148
  embedding_dim: 512
  rnn_type: "GRU" # LSTM or GRU

  # rnn
  input_size: 512 # size of the recurrent neural network
  hidden_size: 512
  num_layers: 3
  dropout: 0

 batch_size: 512
 shuffle: True
 num_epoch: 10
 which_optimizer: adam
 learning_rate: 0.001
 weight_decay: 0.0001