batch_size: 512
dataset_dir: ./chembl/database_smiles_0.5.pkl
learning_rate: 0.001
num_epoch: 10
out_dir: ./generate_result
percentage: 1
rnn_config:
  dropout: 0
  embedding_dim: 512
  hidden_size: 512
  input_size: 512
  num_embeddings: 148
  num_layers: 3
  rnn_type: GRU
shuffle: true
vocab_path: ./vocab/database_selfies_vocab.yaml
weight_decay: 0.0001
which_optimizer: adam
which_vocab: selfies
